FROM python:3.9

RUN apt update && apt install nginx git -y

ENV PYTHONPATH=/app:${PYTHONPATH}
ENV PATH=/app:${PATH}

RUN mkdir -p /app/service
WORKDIR /app

ADD setup.py README.md /app/service/
RUN cd service && pip install -e .[production]

ADD . ./service
ADD ../tests /app/tests

RUN pip install --upgrade fastapi starlette
RUN pip install -r /app/tests/requirements_test.txt
RUN pytest

CMD ["uvicorn", "service.app:app", "--host", "0.0.0.0", "--port", "5000"]